app/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the Closure to execute when that URI is requested.
|
 */

Route::get('/', array('as'      => 'login', 'uses'      => 'UsersController@login'));
Route::get('/login', array('as' => 'login', 'uses' => 'UsersController@login'));
Route::get('users/login', 'UsersController@login');
Route::post('users/login', 'UsersController@doLogin');


Route::get('users/confirm/{code}', 'UsersController@confirm');
Route::get('users/forgot_password', 'UsersController@forgotPassword');
Route::post('users/forgot_password', 'UsersController@doForgotPassword');
Route::get('users/reset_password/{token}', 'UsersController@resetPassword');
Route::post('users/reset_password', 'UsersController@doResetPassword');
Route::get('users/logout', ['as' => 'logout', 'uses' => 'UsersController@logout']);

Route::get('professor/login', array('as' => 'professor.getLogin', 'uses' => 'ProfessorController@getLogin'));
Route::post('professor/login', array('as' => 'professor.login', 'uses' => 'ProfessorController@login'));
Route::get('professor/logout', array('as' => 'professor.logout', 'uses' => 'ProfessorController@logout'));


Route::group(array('before' => 'professor', 'prefix' => 'professor'), function ()
{

    Route::get('/', array('as' => 'professor.index', 'uses' => 'ProfessorController@dashboard'));
    Route::get('minhas-oficinas', array('as' => 'professor.oficinas', 'uses' => 'ProfessorController@oficinas'));
    Route::any('minhas-oficinas/turmas', array('as' => 'professor.turmas', 'uses' => 'ProfessorController@show'));
    Route::any('minhas-oficinas/turmas/chamadaVerso/{id}', array('as' => 'professor.turmas', 'uses' => 'ProfessorController@chamadaVerso'));
    Route::get('minhas-oficinas/turmas/chamada/{id}', array('as' => 'professor.turmas', 'uses' => 'ProfessorController@chamada'));
    Route::get('minhas-oficinas/turmas/alunos/{id}', array('as' => 'professor.turmas', 'uses' => 'ProfessorController@getAlunos'));
    Route::get('minhas-oficinas/turmas/matriculados/{id}', array('as' => 'professor.turmas', 'uses' => 'ProfessorController@getMatriculados'));
    Route::get('minhas-oficinas/turmas/aulas/{id}', array('as' => 'professor.aulas', 'uses' => 'ProfessorController@lancarAula'));
    Route::post('minhas-oficinas/turmas/aulas/{id}', array('uses' => 'ProfessorController@lancarAulaPost'));
    Route::get('minhas-oficinas/turmas/delete/aulas/{aula}', array('as' => 'professor.deleteAula', 'uses' => 'ProfessorController@deleteAula'));
    Route::get('minhas-oficinas/turmas/{id}/aulas/{chamada}', array('as' => 'professor.showAula', 'uses' => 'ProfessorController@showAula'));
});

Route::group(array('before' => 'auth'), function ()
{
        //Route::get('api/oficina', array('as'=>'api.oficina', 'uses'=>'ApiController@getOficina'));
        //Route::get('api/caixa', array('as'=>'api.caixa', 'uses'=>'ApiController@getCaixa'));
        Route::controller('api', 'ApiController');
        Route::get('/admin', array('as' => 'admin', 'uses' => 'AdminController@dashboard'));
        Route::controller('colaboradores', 'ColaboradoresController');
        Route::controller('funcoes', 'FuncoesController');
        Route::controller('religiao', 'ReligioesController');
        Route::controller('etnias', 'EtniasController');
        Route::controller('escolas', 'EscolasController');
        Route::controller('estado-civil', 'EstadoCivilController');
        //Route::controller('alunos', 'AlunosController');
        // Alunos controller
        Route::get('alunos', array('as'=>'alunos', 'uses'=>'AlunosController@index'));
        Route::any('alunos/relatorio/{action?}', array('as'=>'alunos', 'uses'=>'AlunosController@report'));

        Route::any('alunos/relatorioAlunos/{action?}', array('as'=>'alunos', 'uses'=>'AlunosController@newReport'));
        Route::get('alunos/novo', array('as'=>'alunos.novo', 'uses'=>'AlunosController@novo'));
        Route::get('alunos/edit/{id}', array('as'=>'alunos.edit', 'uses'=>'AlunosController@getEdit'));
        Route::get('alunos/autorizacao/{id}', array('as'=>'alunos.autorizacao', 'uses'=>'AlunosController@autorizacao'));
        Route::get('alunos/copy/{id}', array('as'=>'alunos.copy', 'uses'=>'AlunosController@copy'));
        Route::get('alunos/delete/{id}', array('as'=>'alunos.delete', 'uses'=>'AlunosController@delete'));
        Route::post('alunos/save', array('as'=>'alunos.save', 'uses'=>'AlunosController@postSave'));

        Route::get('alunos/export/{id}', array('as'=>'alunos.export', 'uses'=>'AlunosController@getExport'));

        Route::controller('turmas', 'TurmasController');
        Route::controller('oficinas', 'OficinasController');
        Route::controller('relatorios', 'RelatoriosController');

        // menu pedagogico
        Route::group(array('prefix' => 'pedagogico'), function ()
        {
                Route::controller('atendimentos', 'AtendimentosController');
                Route::controller('orientacoes', 'OrientacoesController');
                Route::controller('projetos', 'ProjetosController');
                Route::controller('relatorio-diario', 'RelatorioDiarioController');
                Route::controller('encontros', 'EncontrosController');
                Route::controller('projetos-parceiros', 'ProjetosParceirosController');
        });

        // menu financeiro
        Route::group(array('prefix' => 'financeiro'), function ()
        {
            Route::controller('recurso', 'RecursosController');
            Route::controller('centro', 'CentroController');
            Route::controller('caixa', 'CaixaController');
            Route::controller('conta', 'ContaController');

        });

        // menu financeiro
        Route::group(array('prefix' => 'estoque'), function ()
        {
            Route::controller('produtos', 'ProdutosController');


        });

        // Serviços de Terceiros
        Route::get('/servicos_terceiros', array('as'                 => 'servicos_terceiros', 'uses'                 => 'ServicosTerceirosController@index'));
        Route::get('/servicos_terceiros/delete/{id}', array('as'     => 'excluir_servicos_terceiros', 'uses'     => 'ServicosTerceirosController@delete'));
        Route::get('/servicos_terceiros/{action}/{id?}', array('as'  => 'form_servicos_terceiros', 'uses'  => 'ServicosTerceirosController@form'));
        Route::post('/servicos_terceiros/{action}/{id?}', array('as' => 'salvar_servicos_terceiros', 'uses' => 'ServicosTerceirosController@save'));

        // Formas de pagamento
        Route::get('/formas_pagamento', array('as'                 => 'formas_pagamento', 'uses'                 => 'FormasPagamentosController@index'));
        Route::get('/formas_pagamento/delete/{id}', array('as'     => 'excluir_formas_pagamento', 'uses'     => 'FormasPagamentosController@delete'));
        Route::get('/formas_pagamento/{action}/{id?}', array('as'  => 'form_formas_pagamento', 'uses'  => 'FormasPagamentosController@form'));
        Route::post('/formas_pagamento/{action}/{id?}', array('as' => 'salvar_formas_pagamento', 'uses' => 'FormasPagamentosController@save'));

        // Unidades
        Route::get('/unidades', array('as'                 => 'unidades', 'uses'                 => 'UnidadesController@index'));
        Route::get('/unidades/delete/{id}', array('as'     => 'excluir_unidade', 'uses'     => 'UnidadesController@delete'));
        Route::get('/unidades/{action}/{id?}', array('as'  => 'form_unidade', 'uses'  => 'UnidadesController@form'));
        Route::post('/unidades/{action}/{id?}', array('as' => 'salvar_unidade', 'uses' => 'UnidadesController@save'));

        // Agenda (Eventos)
        Route::get('/eventos', array('as'                 => 'eventos', 'uses'                 => 'AgendaController@index'));
        Route::get('/eventos/delete/{id}', array('as'     => 'excluir_evento', 'uses'     => 'AgendaController@delete'));
        Route::get('/eventos/{action}/{id?}', array('as'  => 'form_evento', 'uses'  => 'AgendaController@form'));
        Route::post('/eventos/{action}/{id?}', array('as' => 'salvar_evento', 'uses' => 'AgendaController@save'));

    });

app/models/Aluno.php
<?php

class Aluno extends \Eloquent
{
    protected $table = 'alunos';
    protected $guarded = array('id');

    public function estadoCivil()
    {
        return $this->belongsTo('EstadoCivil', 'estado_civil_id');
    }

    public function etnia()
    {
        //return $this->belongsTo('User', 'local_key', 'parent_key');
        return $this->belongsTo('Etnia', 'etnia_id');
    }

    public function getDates()
    {
        return array('created_at', 'nascimento');
    }

    public function getNascimentoAttribute()
    {
        return \Carbon::createFromFormat('Y-m-d', $this->attributes['nascimento'])->format('d/m/Y');
    }

    public function setNascimentoAttribute($value)
    {
        if(empty($value))
            return $value;

        $this->attributes['nascimento'] = \Carbon::createFromFormat('d/m/Y', $value)->toDateTimeString();
    }

    public function getIdadeAttribute()
    {

        return (preg_match('/^[0-9]{4}-(0[1-9]|1[0-2])-(0[1-9]|[1-2][0-9]|3[0-1])$/', $this->attributes['nascimento']))
                ? \Carbon::createFromFormat('Y-m-d', $this->attributes['nascimento'])->age
                : '';
    }

    public function religiao()
    {
        return $this->belongsTo('Religiao', 'religiao_id');
    }

    public function escola()
    {
        return $this->belongsTo('Escola', 'escola_id');
    }

    public function turmas()
    {
        return $this->belongsToMany('Turma', 'aluno_turma', 'aluno_id', 'turma_id')->withPivot('motivo', 'cancelado');
    }


}

app/views/alunos/list.blade.php
@extends('layout.admin')

@section('css')
    {{ HTML::style('//cdn.datatables.net/1.9.4/css/jquery.dataTables.css'); }}
    {{ HTML::style('//cdn.datatables.net/tabletools/2.2.0/css/dataTables.tableTools.css'); }}
@stop

@section('js')

    {{ HTML::script('//cdn.datatables.net/1.9.4/js/jquery.dataTables.min.js'); }}
    {{ HTML::script('//cdn.datatables.net/tabletools/2.2.0/js/dataTables.tableTools.min.js'); }}
@stop
@section('content')
    <div class="row">
        <div class="col-sm-12">
            <a href="alunos/novo" class="btn btn-default">Novo Registro</a>
        </div>
    </div>
    {{ Datatable::table()
    ->addColumn('ID','Nome','Escola', 'Turma', 'Opções')       // these are the column headings to be shown
    ->setUrl(url('api/oficina'))
    ->setOptions(
            array(
                'dom' =>"T<'clear'>lfrtip",
                "language" => array("url" => "//cdn.datatables.net/plug-ins/f2c75b7247b/i18n/Portuguese-Brasil.json"),
                'tableTools' => array(
                    "sSwfPath" => "/swf/copy_csv_xls_pdf.swf" ,
                    "aButtons" => array( "pdf", "xls")
                )
            )
        )
    ->render() }}

@stop

app/views/alunos/report.blade.php
@extends('layout.admin')

@section('css')
    {{ HTML::style('//cdn.datatables.net/1.9.4/css/jquery.dataTables.css'); }}
    {{ HTML::style('//cdn.datatables.net/tabletools/2.2.0/css/dataTables.tableTools.css'); }}
@stop

@section('js')
    {{ HTML::script('//cdn.datatables.net/1.9.4/js/jquery.dataTables.min.js'); }}
    {{ HTML::script('//cdn.datatables.net/tabletools/2.2.0/js/dataTables.tableTools.min.js'); }}
@stop

@section('title')
    {{ $title }}
@stop

@section('content')
    <div class="row">
        <div class="col-md-12">
            <form method="post" class="form-inline">
                {{--<div class="form-group">--}}
                    {{--<label for="nome">Nome:</label>--}}
                    {{--{{ Form::number('nome', null, ['placeholder'=>'']) }}--}}
                {{--</div>--}}

                <div class="col-md-12">
                    <div class="form-group">
                        <label for="oficina">Oficina:</label>
                        {{ Form::select('oficina', [''=>'Todas']+$oficinas) }}
                    </div>
                    <div class="form-group">
                        <label for="nome">Sexo:</label>
                        {{ Form::select('sexo', [''=>'Ambos','Masculino'=>'Masculino','Feminino'=>'Feminino']) }}
                    </div>
                    <div class="form-group">
                        <label for="nome">Turno:</label>
                        {{ Form::select('turno', [''=>'Todos','Manhã'=>'Manhã','Tarde'=>'Tarde', 'Noite'=>'Noite', 'Integral'=>'Integral']) }}
                    </div>
                </div>
                <div class="col-md-12">
                    <div class="col-md-8 form-group">
                        <label for="nome">Idade:</label>
                        {{ Form::number('idade_i', null, ['placeholder'=>'mínima', 'class'=>'form-control']) }}
                        {{ Form::number('idade_s', null, ['placeholder'=>'máxima', 'class'=>'form-control']) }}
                        <button type="submit" class="btn btn-primary">Filtrar</button>
                    </div>
                </div>
            </form>
        </div>
    </div>

    <div class="row">
        @if($result)
        <div class="col-sm-6" style="margin-top: 20px">
            Total de Resultados: {{ $count }}
        </div>

        <div class="col-sm-offset-5 col-sm-1" style="margin-top: 20px">
            <a href="relatorio/print{{$qString}}" target="_blank">
                <i class="fa fa-print"></i>
            </a>
            <a href="relatorio/export{{$qString}}">
                <i class="fa fa-file-excel-o"></i>
            </a>
        </div>

        <div class="col-sm-12">
            <table class="table">
            <?php
                $oficina_id = '';
                $turma_id  = '';
            ?>
            @foreach($result as $a)
                @if($a->oficina_id != $oficina_id)
                    <?php
                        $oficina_id = $a->oficina_id;
                    ?>
                    @if($oficina_id != '')
                    <tr>
                        <td colspan="4">&nbsp;</td>
                    </tr>
                    @endif
                    <tr>
                        <td colspan="4"> Oficina: <b>{{ $a->oficina }}</b></td>
                    </tr>
                @endif


                @if($a->turma_id != $turma_id)
                        <?php
                            $turma_id = $a->turma_id;
                        ?>
                        @if($turma_id != '')
                        <tr>
                            <td colspan="4">&nbsp;</td>
                        </tr>
                        @endif

                        <tr>
                            <td colspan="2"> Turma: <b>{{ $a->turma . ' - ' . $a->turno }}</b></td>
                            <td colspan="2"> Colaborador: <b>{{ $a->colaborador }}</b></td>
                        </tr>
                        <tr>
                            <th>Código</th>
                            <th>Nome</th>
                            <th>Sexo</th>
                            <th>Idade</th>
                        </tr>
                @endif

                <tr>
                <td>{{ $a->aluno_id }}</td>
                <td>{{ $a->aluno }}</td>
                <td>{{ (!empty($a->sexo) ? $a->sexo : 'Feminino') }}</td>
                <td>{{ $a->idade }}</td>
                </tr>
            @endforeach
            </table>
        </div>
        <div class="col-sm-12">
            <hr/>
        </div>
        @else
            @if(Request::isMethod('post'))
                <div class="col-sm-12" style="margin-top: 30px;">
                    Nenhum resultado encontrado.
                </div>
            @endif
        @endif
    </div>
@stop

app/views/alunos/report2.blade.php
@extends('layout.admin')

@section('css')
    {{ HTML::style('//cdn.datatables.net/1.9.4/css/jquery.dataTables.css'); }}
    {{ HTML::style('//cdn.datatables.net/tabletools/2.2.0/css/dataTables.tableTools.css'); }}
@stop

@section('js')
    {{ HTML::script('//cdn.datatables.net/1.9.4/js/jquery.dataTables.min.js'); }}
    {{ HTML::script('//cdn.datatables.net/tabletools/2.2.0/js/dataTables.tableTools.min.js'); }}
@stop

@section('title')
    {{ $title }}
@stop

@section('content')
    <div class="row">

        @if($dados)

        <div class="col-sm-12">
            <h3>Relatório de alunos matriculados em 2016</h3>
        </div>

        <div class="col-sm-offset-9 col-sm-3">
            <a href="relatorioAlunos/export">
                <i class="fa fa-file-excel-o"> Gerar em excel</i>
            </a>
        </div>

        <div class="col-sm-12">

            <h4 style="padding: 20px; font-weight: bold;">Total de alunos: {{ $numeroInscritos }}</h4>
            <h4 style="padding: 0 20px 0; font-weight: bold;">Total por sexo:</h4>

            <table style="margin-left: 20px; margin-bottom: 20px">
                <tr>
                    <td>Masculino: &nbsp;</td>
                    <td>{{ $masculino }}</td>
                </tr>
                <tr>
                    <td>Feminino: &nbsp;</td>
                    <td>{{ $feminino }}</td>
                </tr>
                <tr>
                    <td>Outros: &nbsp;</td>
                    <td>{{ $outros }}</td>
                </tr>
            </table>

            <table class="table">
                <?php $oficina = ''; ?>

                @foreach($dados as $a)
                    @if($a->oficina != $oficina)
                        @if($oficina != '')
                        <tr>
                            <td colspan="4">&nbsp;</td>
                        </tr>
                        @endif
                        <tr>
                            <td colspan="4"> Oficina: <b>{{ $a->oficina }}</b></td>
                        </tr>
                        <?php $oficina = $a->oficina; ?>
                        <tr>
                            <th></th>
                            <th>Cód.</th>
                            <th>Nome</th>
                            <th>Sexo</th>
                    @endif

                    @if(!empty($a->aluno))
                        <tr>
                            <td>&nbsp;&nbsp;&nbsp;</td>
                            <td>{{ $a->id }}</td>
                            <td>{{ $a->aluno }}</td>
                            <td>{{ $a->sexo }}</td>
                        </tr>
                    @endif
                @endforeach
            </table>

        </div>
            <div class="col-sm-12">
            <hr/>
                </div>

        @endif
    </div>

@stop